### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by lext** [imedslab/solt#34]

**Comment by aisosalo** [comment]
```yaml
{% set name = "solt" %}
{% set version = "0.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solt-{{ version }}.tar.gz  # PyPI
  #url: https://github.com/Oulu-IMEDS/solt/archive/refs/tags/v0.1.9.tar.gz
  ##url: https://github.com/Oulu-IMEDS/solt/releases/download/v{{ version }}/solt-{{ version }}.tar.gz
  sha256: d6c665f530afd531c176c58a98309bcebcf0d5a8b3741cc85a7afbae41eb6e13

build:
  number: 0
  noarch: python
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  run:
    - numpy
    - opencv-python-headless
    - python
    - pyyaml
    - scipy
    - torch
    - torchvision

test:
  imports:
    - solt
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://oulu-imeds.github.io/solt/
  summary: Optimized data augmentation library for Deep Learning
  description: |
    Data augmentation library for Deep Learning, which supports images, 
    segmentation masks, labels and keypoints. Furthermore, SOLT is fast 
    and has OpenCV in its backend. Full auto-generated docs and 
    examples are available here: https://mipt-oulu.github.io/solt/.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://oulu-imeds.github.io/solt/
  dev_url: https://github.com/Oulu-IMEDS/solt

extra:
  recipe-maintainers: # GitHub IDs for maintainers of the recipe
    - lext
```
